kata: dispatcher Class Reference
dispatcher Class Reference
Public Member Functions
__construct ()
__destruct ()
dispatch ($url, $routes=null)
fourohfour ()
Data Fields
$params
$controller
Detailed Description
Definition at line 20 of file dispatcher.php.
Constructor & Destructor Documentation
__construct ()
constructor, just initializes starttime
Definition at line 51 of file dispatcher.php.
__destruct ()
destructor, outputs Total Render time if DEBUG>0
Definition at line 58 of file dispatcher.php.
References classRegistry::getLoadedClasses().
Member Function Documentation
dispatch ($ url, $ routes = null) [final]
start the actual mvc-machinery 1. constructs all needed params by calling constructParams 2. loads the controller 3. sets all needed variables of the controller 4. calls constructClasses of the controller, which in turn constructs all needed models and components 5. render the actual view and layout (if autoRender is true) 6. return the output
Parameters:
string $url raw url string passed to the array (eg. /main/index/foo/bar)
Definition at line 83 of file dispatcher.php.
References fourohfour(), and kataUse().
fourohfour ()
Definition at line 159 of file dispatcher.php.
Referenced by dispatch().
Field Documentation
$controller
Definition at line 41 of file dispatcher.php.
$params
Definition at line 35 of file dispatcher.php.
The documentation for this class was generated from the following file:
dispatcher.php