kata: classRegistry Class Reference
classRegistry Class Reference
Static Public Member Functions
static & getObject ($name, $key='')
static getLoadedClasses ()
Detailed Description
Definition at line 20 of file class_registry.php.
Member Function Documentation
static getLoadedClasses () [static]
return all classes in the cache. used for debugging
Returns:
array cache-array
Definition at line 47 of file class_registry.php.
Referenced by dispatcher::__destruct().
static& getObject ($ name, $ key = '') [static]
return an instance of the class given in $name. If the class does not exist yet, create it.
Parameters:
string $name name of the class to return an instance of
string $key to create the same class more than once. uses simple caching to return consistency
Definition at line 34 of file class_registry.php.
Referenced by __(), Controller::_constructClasses(), Controller::_constructComponents(), View::constructHelpers(), getModel(), getUtil(), and Model::setupDbo().
The documentation for this class was generated from the following file:
class_registry.php