kata: CacheUtility Class Reference
CacheUtility Class Reference
Public Member Functions
initialize ()
getMethodUsed ()
getMemcacheStats ()
__destruct ()
add ($id, $data, $ttl=0, $forceMethod=false)
write ($id, $data, $ttl=0, $forceMethod=false)
read ($id, $forceMethod=false)
disableRequestCache ()
enableRequestCache ()
Data Fields
const CM_FILE = 'file'
const CM_EACC = 'eacc'
const CM_APC = 'apc'
const CM_XCACHE = 'xcache'
const CM_MEMCACHE = 'memcache'
Detailed Description
Definition at line 17 of file cacheutility.php.
Constructor & Destructor Documentation
__destruct ()
output debugging data if needed
Definition at line 128 of file cacheutility.php.
Member Function Documentation
add ($ id, $ data, $ ttl = 0, $ forceMethod = false)
Definition at line 142 of file cacheutility.php.
References initialize(), kataGetLineInfo(), and kataGetValueInfo().
disableRequestCache ()
Disables the request cache
Definition at line 253 of file cacheutility.php.
enableRequestCache ()
Enables the request cache
Definition at line 260 of file cacheutility.php.
getMemcacheStats ()
Definition at line 114 of file cacheutility.php.
getMethodUsed ()
Returns:
int caching-method used for the last read/write
Definition at line 87 of file cacheutility.php.
initialize ()
set first store/read-method as default
Definition at line 43 of file cacheutility.php.
References kataMakeTmpPath().
Referenced by add(), read(), and write().
read ($ id, $ forceMethod = false)
Definition at line 204 of file cacheutility.php.
References initialize(), kataGetLineInfo(), and kataGetValueInfo().
write ($ id, $ data, $ ttl = 0, $ forceMethod = false)
Definition at line 173 of file cacheutility.php.
References initialize(), kataGetLineInfo(), and kataGetValueInfo().
Field Documentation
const CM_APC = 'apc'
Definition at line 35 of file cacheutility.php.
const CM_EACC = 'eacc'
Definition at line 34 of file cacheutility.php.
const CM_FILE = 'file'
some internal constants
Definition at line 33 of file cacheutility.php.
Referenced by Model::describe().
const CM_MEMCACHE = 'memcache'
Definition at line 37 of file cacheutility.php.
Referenced by ClusterlockUtility::lock(), and ClusterlockUtility::unlock().
const CM_XCACHE = 'xcache'
Definition at line 36 of file cacheutility.php.
The documentation for this class was generated from the following file:
cacheutility.php