kata: SessionComponent Class Reference
SessionComponent Class Reference
Public Member Functions
startup (&$controller)
__construct ()
read ($name=null)
write ($name, $value)
writeArray ($arr)
delete ($name)
getIp ()
destroy ()
startup (&$controller)
__construct ()
read ($name=null)
write ($name, $value)
delete ($name)
getIp ()
destroy ()
startup (&$controller)
__construct ()
read ($name=null)
write ($name, $value)
delete ($name)
getIp ()
destroy ()
Data Fields
$controller = false
$components = array()
Detailed Description
Definition at line 16 of file client.session.php.
Constructor & Destructor Documentation
__construct ()
default constructor. initializes some variables needed to construct a session and tries to start/continue a session, throws exception if that fails
Definition at line 97 of file client.session.php.
__construct ()
default constructor. initializes some variables needed to construct a session and tries to start/continue a session, throws exception if that fails
Definition at line 97 of file file.session.php.
References kataMakeTmpPath().
__construct ()
default constructor. initializes some variables needed to construct a session and tries to start/continue a session, throws exception if that fails
Definition at line 134 of file memcached.session.php.
Member Function Documentation
delete ($ name)
delete values stored under given name from the session-container
Parameters:
string $name identifier
Definition at line 240 of file memcached.session.php.
delete ($ name)
delete values stored under given name from the session-container
Parameters:
string $name identifier
Definition at line 181 of file file.session.php.
delete ($ name)
delete values stored under given name from the session-container
Parameters:
string $name identifier
Definition at line 227 of file client.session.php.
destroy ()
destroy any current session and all variables stored in the session-container with it
Definition at line 269 of file memcached.session.php.
destroy ()
destroy any current session and all variables stored in the session-container with it
Definition at line 210 of file file.session.php.
destroy ()
destroy any current session and all variables stored in the session-container with it
Definition at line 257 of file client.session.php.
getIp ()
try to do an educated guess about the users real ip, even if he is behind proxies
Definition at line 261 of file memcached.session.php.
References getUtil().
getIp ()
try to do an educated guess about the users real ip, even if he is behind proxies
Definition at line 202 of file file.session.php.
References getUtil().
getIp ()
try to do an educated guess about the users real ip, even if user is behind proxies
Definition at line 249 of file client.session.php.
References getUtil().
Referenced by startup().
read ($ name = null)
read value(s) from the session container. returns all currently set values if called with null returns null when nothing could be found under the name you gave
Parameters:
string $name name under which the value(s) are to find
Definition at line 206 of file memcached.session.php.
read ($ name = null)
read value(s) from the session container. returns all currently set values if called with null returns null when nothing could be found under the name you gave
Parameters:
string $name name under which the value(s) are to find
Definition at line 147 of file file.session.php.
read ($ name = null)
read value(s) from the session container. returns all currently set values if called with null returns null when nothing could be found under the name you gave
Parameters:
string $name name under which the value(s) are to find
Definition at line 178 of file client.session.php.
startup (&$ controller)
perform needed initialization and cache the controller that called us
Definition at line 92 of file memcached.session.php.
References $controller, env(), and getIp().
startup (&$ controller)
perform needed initialization and cache the controller that called us
Definition at line 55 of file file.session.php.
References $controller, env(), and getIp().
startup (&$ controller)
perform needed initialization and cache the controller that called us
Definition at line 57 of file client.session.php.
References $controller, env(), and getIp().
write ($ name, $ value)
write mixed values to the session-component.
Parameters:
string $name identifier, may contain alphanumeric characters or .-_
mixed $value values to store
Definition at line 226 of file memcached.session.php.
write ($ name, $ value)
write mixed values to the session-component.
Parameters:
string $name identifier, may contain alphanumeric characters or .-_
mixed $value values to store
Definition at line 167 of file file.session.php.
write ($ name, $ value)
write mixed values to the session-component.
Parameters:
string $name identifier, may contain alphanumeric characters or .-_
mixed $value values to store
Definition at line 200 of file client.session.php.
writeArray ($ arr)
write multiple key value arrays to session-component
Parameters:
$arr array with key-value pairs
Definition at line 215 of file client.session.php.
Field Documentation
$components = array()
Definition at line 28 of file client.session.php.
$controller = false
Definition at line 22 of file client.session.php.
Referenced by startup().
The documentation for this class was generated from the following files:
client.session.php
file.session.php
memcached.session.php