kata: JSMin Class Reference
JSMin Class Reference
Public Member Functions
__construct ($input)
Static Public Member Functions
static minify ($js)
Data Fields
const ORD_LF = 10
const ORD_SPACE = 32
Protected Member Functions
action ($d)
get ()
isAlphaNum ($c)
min ()
next ()
peek ()
Protected Attributes
$a = ''
$b = ''
$input = ''
$inputIndex = 0
$inputLength = 0
$lookAhead = null
$output = ''
Detailed Description
Definition at line 117 of file minifyutility.php.
Constructor & Destructor Documentation
__construct ($ input)
Definition at line 138 of file minifyutility.php.
References $input.
Member Function Documentation
action ($ d) [protected]
Definition at line 145 of file minifyutility.php.
References next().
Referenced by min().
get () [protected]
Definition at line 204 of file minifyutility.php.
isAlphaNum ($ c) [protected]
Definition at line 228 of file minifyutility.php.
Referenced by min().
min () [protected]
Definition at line 232 of file minifyutility.php.
References action(), and isAlphaNum().
static minify ($ js) [static]
Definition at line 131 of file minifyutility.php.
Referenced by MinifyUtility::js().
next () [protected]
Definition at line 313 of file minifyutility.php.
References peek().
Referenced by action().
peek () [protected]
Definition at line 352 of file minifyutility.php.
Referenced by next().
Field Documentation
$a = '' [protected]
Definition at line 121 of file minifyutility.php.
$b = '' [protected]
Definition at line 122 of file minifyutility.php.
$input = '' [protected]
Definition at line 123 of file minifyutility.php.
Referenced by __construct().
$inputIndex = 0 [protected]
Definition at line 124 of file minifyutility.php.
$inputLength = 0 [protected]
Definition at line 125 of file minifyutility.php.
$lookAhead = null [protected]
Definition at line 126 of file minifyutility.php.
$output = '' [protected]
Definition at line 127 of file minifyutility.php.
const ORD_LF = 10
Definition at line 118 of file minifyutility.php.
const ORD_SPACE = 32
Definition at line 119 of file minifyutility.php.
The documentation for this class was generated from the following file:
minifyutility.php