kata: Helper Class Reference
Helper Class Reference
Public Member Functions
__construct ()
urlRel ($url=null)
url ($url=null)
urlAbs ($url=null)
parseAttributes ($options, $exclude=null, $insertBefore= ' ', $insertAfter=null)
urlWebroot ($url)
Data Fields
$action
$webroot
$params
$tags = null
$base = null
$basePath = null
$vars = null
Detailed Description
Definition at line 18 of file helper.php.
Constructor & Destructor Documentation
__construct ()
constructor, loads tags-templates from config folder
Definition at line 72 of file helper.php.
References $tags.
Member Function Documentation
parseAttributes ($ options, $ exclude = null, $ insertBefore = ' ', $ insertAfter = null)
build an attribute-string of an html-tag out of an array
Parameters:
array $options the name=>value pairs to append to the tag
mixed $exlude null or array of attribute-names not to append (eg. when they are framework-parameters, not html-attributes)
string $insertBefore string to prepand
mixed $insertAfter string to append, or null if you want nothing appended
Returns:
string attributes as html
Definition at line 157 of file helper.php.
References am().
Referenced by HtmlHelper::image(), HtmlHelper::link(), and HtmlHelper::selectTag().
url ($ url = null)
shortcut. this is what your are normally using everywhere inside a view
Parameters:
string $url url to expand
Returns:
string
Definition at line 125 of file helper.php.
References urlAbs().
Referenced by HtmlHelper::image(), HtmlHelper::link(), HtmlHelper::tokenUrl(), and urlWebroot().
urlAbs ($ url = null)
construct an absolute url (including http(s)) with the base url of the framework. normally needed if you send a view via email and you need the http-part
Parameters:
string $url url to expand
Returns:
string
Definition at line 134 of file helper.php.
Referenced by url().
urlRel ($ url = null)
construct an relative url with the base url of the framework
Parameters:
string $url url to expand
Returns:
string
Definition at line 96 of file helper.php.
urlWebroot ($ url)
Deprecated:
1.1 - 09.11.2008 not needed anymore. use url() instead
Returns:
string
Definition at line 228 of file helper.php.
References url().
Field Documentation
$action
Definition at line 24 of file helper.php.
$base = null
Definition at line 57 of file helper.php.
$basePath = null
Definition at line 62 of file helper.php.
$params
Definition at line 46 of file helper.php.
$tags = null
placeholder for the tag-templates inside the config folder
Parameters:
array
Definition at line 52 of file helper.php.
Referenced by __construct().
$vars = null
Definition at line 67 of file helper.php.
$webroot
Definition at line 30 of file helper.php.
The documentation for this class was generated from the following file:
helper.php