kata: ScaffoldController Class Reference
ScaffoldController Class Reference
Public Member Functions
beforeDelete ($id=null)
beforeUpdate ($id=null)
beforeInsert ($data=null)
beforeAction ()
beforeFilter ()
afterFilter ()
index ($page=0)
delete ($id=null, $page=0)
update ($id=null)
insert ()
Detailed Description
Definition at line 17 of file scaffold_controller.php.
Member Function Documentation
afterFilter ()
Called just after the view was rendered. Is never called if autoRender is false. Can be used to manipulate the views contents in the controllers output-property
Reimplemented from Controller.
Definition at line 41 of file scaffold_controller.php.
beforeAction ()
call this after the controller has been initialized (read: models, components etc contructed) and we are about to call the myaction() method of the controller
Reimplemented from Controller.
Definition at line 35 of file scaffold_controller.php.
beforeDelete ($ id = null)
Definition at line 21 of file scaffold_controller.php.
Referenced by delete().
beforeFilter ()
Called just before the view is rendered. Is never called if autoRender is false
Reimplemented from Controller.
Definition at line 38 of file scaffold_controller.php.
beforeInsert ($ data = null)
Definition at line 29 of file scaffold_controller.php.
Referenced by insert().
beforeUpdate ($ id = null)
Definition at line 25 of file scaffold_controller.php.
Referenced by update().
delete ($ id = null, $ page = 0) [final]
Definition at line 65 of file scaffold_controller.php.
References beforeDelete(), and Controller::redirect().
index ($ page = 0) [final]
Definition at line 55 of file scaffold_controller.php.
References Controller::render().
insert () [final]
Definition at line 108 of file scaffold_controller.php.
References beforeInsert(), Controller::redirect(), and Controller::render().
update ($ id = null) [final]
Definition at line 77 of file scaffold_controller.php.
References beforeUpdate(), Controller::redirect(), and Controller::render().
The documentation for this class was generated from the following file:
scaffold_controller.php