kata: dbo_mssql Class Reference
dbo_mssql Class Reference
Public Member Functions
connect ()
isConnected ()
getLink ()
setLink ($l)
setEncoding ($enc)
& query ($s, $idnames=false)
escape ($sql)
__destruct ()
getPageQuery ($sql, $page, $perPage)
makeDateTime ($t)
& describe ($tableName)
Data Fields
$dbconfig = null
$quoteLeft = '['
$quoteRight = ']'
Detailed Description
Definition at line 21 of file dbo_mssql.php.
Constructor & Destructor Documentation
__destruct ()
output any queries made, how long it took, the result and any errors if DEBUG
Definition at line 267 of file dbo_mssql.php.
Member Function Documentation
connect ()
connect to the database
Definition at line 63 of file dbo_mssql.php.
References $res.
Referenced by getLink().
& describe ($ tableName)
try to reduce the fields of given table to the basic types bool, unixdate, int, string, float, date, enum
example:
Array ([table] => test [primary] => a [cols] => Array ([a] => Array ([default] => CURRENT_TIMESTAMP [null] => [unique] => [length] => 0 [type] => date)
[g] => Array ([default] => [null] => [unique] => [length] => 0 [type] => unsupported:time)
[j] => Array ([default] => [null] => [unique] => [length] => 0 [type] => enum [values] => Array ([0] => a [1] => B [2] => c)
)
)
)
Parameters:
string $tableName name of the table to analyze
Returns:
unknown
Definition at line 362 of file dbo_mssql.php.
References getLink().
escape ($ sql)
escape the given string so it can be safely appended to any sql
Parameters:
string $sql string to escape
Returns:
string
Definition at line 260 of file dbo_mssql.php.
getLink ()
return the current link to the database, connect first if needed
Definition at line 91 of file dbo_mssql.php.
References connect().
Referenced by describe().
getPageQuery ($ sql, $ page, $ perPage)
build a sql-string that returns paged data
Returns:
string finished query
Definition at line 296 of file dbo_mssql.php.
isConnected ()
Definition at line 84 of file dbo_mssql.php.
makeDateTime ($ t)
return the sql needed to convert a unix timestamp to datetime
Parameters:
integer $t unixtime
Returns:
string
Definition at line 305 of file dbo_mssql.php.
& query ($ s, $ idnames = false)
execute query and return useful data depending on query-type
Parameters:
string $s sql-statement
string $idname which field-value to use as the key of the returned array (false=dont care)
Returns:
array
Definition at line 212 of file dbo_mssql.php.
setEncoding ($ enc)
unused right now, later possibly used by model to set right encoding
Definition at line 133 of file dbo_mssql.php.
setLink ($ l)
Definition at line 98 of file dbo_mssql.php.
Field Documentation
$dbconfig = null
Definition at line 27 of file dbo_mssql.php.
$quoteLeft = '['
constants used to quote table and field names
Definition at line 57 of file dbo_mssql.php.
$quoteRight = ']'
Definition at line 58 of file dbo_mssql.php.
The documentation for this class was generated from the following file:
dbo_mssql.php